name: "LlamaLocker"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "21.2.0"
          cache: "pnpm"
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: pnpm install
      - run: pnpm check
      - run: forge --version
      - run: forge build --sizes
      - run: forge test -vvv
